Add routing rule test
futurewei-cloud/python-alcorclient pull request #1
Opened 2021-08-10 15:11 UTC by DavidLiu506

2021-08-10 19:03 UTC, cj-chung commented on neutronclient/v2_0/client.py
> +        return self.put((self.router_path % router) + "/add_extra_routes",
@DavidLiu506 please make a note here, the current `add_extra_routes` is not compatible with the latest neutron api. If we need to 100% compatible with latest neutron, we should modify our api to use `add_extraroutes`.

2021-08-10 19:03 UTC, cj-chung commented on neutronclient/v2_0/client.py
> +                        body=body)
@DavidLiu506 Should we put another layer of API in rally's neutron.py? In that way, we can have a consistent way to call neutronclient's api from rally.

2021-08-10 21:39 UTC, DavidLiu506 commented on neutronclient/v2_0/client.py
> +                        body=body)
Already follow rally test layer to do rally test. First write plugins to call rally (there two layers) and rally call this api talk to alcor. Same as rally-openstack.

2021-08-10 22:02 UTC, DavidLiu506 commented on neutronclient/v2_0/client.py
> +                        body=body)
@cj-chung Thanks for your review. Forgot copy this lay to PR.

2021-08-11 16:37 UTC, xieus commented on neutronclient/v2_0/client.py
> +        return self.put((self.router_path % router) + "/add_extra_routes",
Just curious about the difference about our current implementation and the latest Neutron add_extraroutes apis. If not much, let us make it compatible.

2021-08-11 18:42 UTC, xieus commented
@DavidLiu506 A general feedback: could you please add description to a PR including this one and others going forward? In this way, we could always trace back to a PR later on. Thank you.

2021-08-11 22:25 UTC, DavidLiu506 commented
@xieus Thanks for your suggestion.

Will work on it.

2021-08-13 17:45 UTC, cj-chung requested changes

2021-08-13 17:45 UTC, cj-chung commented on neutronclient/v2_0/client.py
> +        return self.put((self.router_path % router) + "/add_extra_routes",
@DavidLiu506 Please make change in Route Manager for these APIs in order to compatible with latest Neutron version.

2021-08-17 00:01 UTC, cj-chung approved these changes
LGTM

2021-08-20 14:01 UTC, merged